name: Version increment development branch

on:
  push:
    branches: [ "development" ]

# Possible options are [ major | feature | bug | alpha | beta | rc ]

jobs:
  IncrementVersion:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Check the last commit message for feature increment
      uses: actions-ecosystem/action-regex-match@v2
      id: feature-match
      with:
        text: ${{ github.event.head_commit.message }}
        regex: '/feature/|feature/'
    
    - name: Check the last commit message for bugfix increment
      uses: actions-ecosystem/action-regex-match@v2
      id: bugfix-match
      with:
        text: ${{ github.event.head_commit.message }}
        regex: '/bugfix/|bugfix/'
      
    - name: Extract increment option
      run: echo ${{ steps.regex-match.outputs.match }}
      
    - if: ${{ steps.feature-match.outputs.match == '' }} && ${{ steps.bugfix-match.outputs.match == '' }}
      run: exit 1
    
    - if: ${{ steps.feature-match.outputs.match != '' }}
      id: version-increment
      run:
        echo "${{ steps.feature-match.outputs.match }} in message found"
        echo '::set-output name=fragment::feature'
      
    - if: ${{ steps.bugfix-match.outputs.match != '' }}
      run:
        echo "${{ steps.bugfix-match.outputs.match }} in message found"
        echo '::set-output name=fragment::bug'
    
    - name: Check result
      run: echo ${{ steps.version-increment-regexp-match.outputs.match }}
      if: ${{ steps.regex-match.outputs.match == '' }}
        echo "Failed to extract version increment"
        exit 1
    
    - name: Read VERSION file
      uses: juliangruber/read-file-action@v1
      id: template
      with:
        path: ./VERSION.txt
        
    - run: echo "${{ steps.template.outputs.content }}"

    - name: Increment version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ steps.template.outputs.content }}
        version-fragment: ${{ steps.version-increment.outputs.fragment }}
    
    - name: Write new version to file
      uses: DamianReeves/write-file-action@master
      with:
        path: ./VERSION.txt
        contents: ${{ steps.bump_version.outputs.next-version }}
        write-mode: 'overwrite'

    - name: Commit changes
      uses: test-room-7/action-update-file@v1
      with:
          file-path: VERSION.txt
          commit-msg: "[set version ${{ steps.bump_version.outputs.next-version }}]"
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create tag if major release
      if: ${{ steps.version-increment-regexp-match.outputs.match == 'major' }}
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "release-${{ steps.bump_version.outputs.next-version }}"
        
