#- name: Check directory contents
#  run: |
#    ls -la

name: Version increment

on:
  push:
    branches: [ "main" ]

env:
  # valid arguments: [ 'major' 'feature' 'bug' 'alpha' 'beta' 'rc' ]
  VERSION_FRAGMENT: 'feature'

jobs:
  Check_commit_message_format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '\[[^]]+\] .+$'
        flags: 'gm'
        error: 'Your first line has to contain a commit type like "[BUGFIX]".'
    - if: failure()
      run: exit 1
      
    - name: Check BUGFIX
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '\[feature]'
    - if: success()
      run: echo "success"

  Increment_version:
    needs: Check_commit_message_format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Read VERSION file
      uses: juliangruber/read-file-action@v1
      id: template
      with:
        path: ./VERSION.txt

    - name: Get the template output
      run: echo "${{ steps.template.outputs.content }}"

    - name: Increment version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ steps.template.outputs.content }}
        version-fragment: ${{ env.VERSION_FRAGMENT }}
    
    - name: Write version to file
      uses: DamianReeves/write-file-action@master
      with:
        path: ./VERSION.txt
        contents: ${{ steps.bump_version.outputs.next-version }}
        write-mode: 'overwrite'

    - name: Commit changes
      uses: test-room-7/action-update-file@v1
      with:
          file-path: VERSION.txt
          commit-msg: "[SET VERSION ${{ steps.bump_version.outputs.next-version }}]"
          github-token: ${{ secrets.GITHUB_TOKEN }}
